import os, sys, argparse, tabulate, pickle


def loadTable(reportpkl):
    reportDict = {}
    if os.path.exists(reportpkl):
        with open(reportpkl, "rb") as pkf:
            reportDict = pickle.load(pkf)
    return reportDict


if __name__ == "__main__":
    msg = "The script to diff and combine reports generated by e2eshark run.pl"
    parser = argparse.ArgumentParser(description=msg, epilog="")
    parser.add_argument(
        "inputdirs",
        nargs="*",
        help="Input test run directory names",
    )
    parser.add_argument(
        "-d",
        "--diff",
        action="store_true",
        help="Diff the reports in the given run directories",
    )
    parser.add_argument(
        "-u",
        "--union",
        action="store_true",
        help="Create a union of reports in the given run directories",
    )
    parser.add_argument(
        "-t",
        "--type",
        choices=["status", "time"],
        default="status",
        help="Process status report vs time report",
    )

    args = parser.parse_args()
    dirlist = args.inputdirs
    reportdict = {}
    for item in dirlist:
        rundir = os.path.abspath(item)
        if not os.path.exists(rundir):
            print("The given file ", rundir, " does not exist\n")
            sys.exit(1)
        if args.type == "time":
            reportpkl = rundir + "/timereport.pkl"
        else:
            reportpkl = rundir + "/statusreport.pkl"

        if not os.path.exists(reportpkl):
            print(f"{reportpkl} does not exist. This report will be ignored.")
            continue
        reportdict[rundir] = loadTable(reportpkl)
        print(reportdict[rundir])

    print(f"Still under construction")
    sys.exit(1)
