# Copyright 2024 Advanced Micro Devices
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: E2EAMDSHARK Test Suite Duplicate models
on:
  workflow_dispatch:
  # schedule:
  # # Runs at 6:30 AM PST on every Sunday
  #  - cron: '30 13 * * 0'

jobs:
  e2eamdshark:
    timeout-minutes: 600
    name: "Models :: ${{ matrix.backend }} :: ${{ matrix.test-file }}"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: mi325_gpu1_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: nlp-shard1_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu2_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: nlp-shard2_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu3_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: nlp-shard3_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu4_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: amdshark-test-suite_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu5_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: vai-hf-cnn-fp32-shard1_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu6_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: vai-hf-cnn-fp32-shard2_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu7_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: vai-hf-cnn-fp32-shard3_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu8_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: vai-int8-p0p1-shard1_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu9_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: vai-int8-p0p1-shard2_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu10_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: vai-int8-p0p1-shard3_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu11_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: vai-vision-int8_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu12_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: migraphx_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu13_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_computer_vision_1_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu14_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_computer_vision_2_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu15_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_computer_vision_3_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu16_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_computer_vision_4_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu17_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_computer_vision_5_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu18_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_gen_ai_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu19_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_graph_ml_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu20_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_nlp_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: mi325_gpu21_test
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            device: hip
            target-chip: gfx942
            test-file: onnx_model_zoo_validated_vision_others
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache

          # - name: mi325_gpu13_test
          #   runs-on: linux-mi325-1gpu-ossci-nod-ai
          #   backend: hip
          #   device: hip
          #   target-chip: gfx942
          #   test-file: onnxrt-iree-ep
          #   cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: cpu_shard1_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: nlp-shard1_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard2_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: nlp-shard2_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard3_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: nlp-shard3_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard4_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: amdshark-test-suite_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard5_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: vai-hf-cnn-fp32-shard1_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard6_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: vai-hf-cnn-fp32-shard2_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard7_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: vai-hf-cnn-fp32-shard3_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard8_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: vai-int8-p0p1-shard1_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard9_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: vai-int8-p0p1-shard2_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard10_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: vai-int8-p0p1-shard3_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard11_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: vai-vision-int8_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard12_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: migraphx_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard13_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_computer_vision_1_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard14_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_computer_vision_2_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard15_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_computer_vision_3_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard16_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_computer_vision_4_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard17_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_computer_vision_5_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard18_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_gen_ai_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard19_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_graph_ml_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard20_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_nlp_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
          - name: cpu_shard21_test
            runs-on: nodai-cpu-x86-64
            backend: llvm-cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            test-file: onnx_model_zoo_validated_vision_others
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
    defaults:
      run:
        shell: bash
          # - name: cpu_shard13_test
          #   runs-on: nodai-cpu-x86-64
          #   backend: llvm-cpu
          #   device: local-task
          #   target-chip: x86_64-linux-gnu
          #   test-file: onnxrt-iree-ep
          #   cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
    env:
      E2E_VENV_DIR: ${{ github.workspace }}/test-suite_venv
      EP_VENV_DIR: ${{ github.workspace }}/ep_venv
      ALT_E2E_VENV_DIR: ${{ github.workspace }}/alt-test-suite_venv
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      AZ_PRIVATE_CONNECTION: ${{ secrets.ONNXPRIVATESTORAGE_AZ_PRIVATE_CONNECTION }}
      CACHE_DIR: ${{ matrix.cache-dir }}
    steps:
      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: Checkout Test Suite
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: nod-ai/AMD-SHARK-TestSuite
          path: test-suite

      - name: "Setup alt e2eamdshark python venv"
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 30
          max_attempts: 2
          retry_on: error
          shell: bash
          on_retry_command: echo "::warning::Setup venv failed, retrying..."
          command: |
            cd ./test-suite
            rm -rf ${ALT_E2E_VENV_DIR}
            sudo apt update
            sudo apt install wget
            python -m venv ${ALT_E2E_VENV_DIR}
            source ${ALT_E2E_VENV_DIR}/bin/activate
            pip install --upgrade pip
            pip install -r ./alt_e2eamdshark/base_requirements.txt
            pip install -r ./alt_e2eamdshark/iree_requirements.txt
            pip install --no-deps -r ./alt_e2eamdshark/torch_mlir_requirements.txt
            pip install --pre --upgrade iree-base-compiler iree-base-runtime -f https://iree.dev/pip-release-links.html

      #- name: "Setup IREE EP python venv"
      #  run: |
      #    python -m venv ${EP_VENV_DIR}
      #    source ${EP_VENV_DIR}/bin/activate
      #    pip install --upgrade pip
      #    pip install -r ./alt_e2eamdshark/base_requirements.txt
      #    pip install -r ./alt_e2eamdshark/iree_requirements.txt
      #    pip install --no-deps -r ./alt_e2eamdshark/torch_mlir_requirements.txt
      #    pip uninstall -y onnxruntime
      #    wget https://amdsharkpublic.blob.core.windows.net/amdsharkpublic/onnxruntime/pip_whl/onnxruntime-1.20.0-cp311-cp311-linux_x86_64.whl
      #    pip install ./onnxruntime-1.20.0-cp311-cp311-linux_x86_64.whl
      #  working-directory: ./test-suite

      - name: Run Onnx Bench Mode
        if: contains(matrix.test-file, 'migraphx')
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 120
          max_attempts: 2
          retry_on: error
          shell: bash
          on_retry_command: echo "::warning::Onnx bench mode failed, retrying..."
          command: |
            cd ./test-suite
            source ${ALT_E2E_VENV_DIR}/bin/activate
            pip freeze
            cd alt_e2eamdshark
            free -mh
            python ./run.py \
              -r ./test-onnx \
              --report \
              --testsfile onnx_tests/models/external_lists/${{ matrix.test-file }}.txt \
              -b ${{ matrix.backend }} \
              -d ${{ matrix.device }} \
              -c ${{ matrix.target-chip }} \
              --report-file reports/${{ matrix.test-file }}.md \
              --mode=cl-onnx-iree \
              --cleanup=3 \
              --benchmark \
              --get-metadata \
              -v
            python utils/find_duplicate_models.py -s -r ./test-onnx -o reports/duplicates.json

      - name: Run Onnx Default Mode
        if: ${{ ! contains(matrix.test-file, 'migraphx') && ! contains(matrix.test-file, 'onnxrt-iree-ep') }}
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 120
          max_attempts: 2
          retry_on: error
          shell: bash
          on_retry_command: echo "::warning::Onnx default mode failed, retrying..."
          command: |
            cd ./test-suite
            source ${ALT_E2E_VENV_DIR}/bin/activate
            pip freeze
            cd alt_e2eamdshark
            free -mh
            python ./run.py \
              -r ./test-onnx \
              --report \
              --testsfile onnx_tests/models/external_lists/${{ matrix.test-file }}.txt \
              -b ${{ matrix.backend }} \
              -d ${{ matrix.device }} \
              -c ${{ matrix.target-chip }} \
              --report-file reports/${{ matrix.test-file }}.md \
              --mode=cl-onnx-iree \
              --cleanup=3 \
              --get-metadata \
              -v
            python utils/find_duplicate_models.py -s -r ./test-onnx -o reports/duplicates.json

      - name: Run OnnxRT IREE EP
        if: contains(matrix.test-file, 'onnxrt-iree-ep')
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 120
          max_attempts: 2
          retry_on: error
          shell: bash
          on_retry_command: echo "::warning::OnnxRT IREE EP failed, retrying..."
          command: |
            cd ./test-suite
            source ${EP_VENV_DIR}/bin/activate
            export COMPILER_PATH=$(python -c "import iree.compiler as _; print(_.__path__[0])")
            export LD_LIBRARY_PATH="$COMPILER_PATH/_mlir_libs/"
            echo "COMPILER_PATH=$COMPILER_PATH" >> $GITHUB_ENV
            echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
            pip freeze
            cd alt_e2eamdshark
            free -mh
            python ./run.py -m ort-ep \
              -r ./test-onnx \
              --report \
              --testsfile onnx_tests/models/external_lists/${{ matrix.test-file }}.txt \
              -b ${{ matrix.backend }} \
              -d ${{ matrix.device }} \
              -c ${{ matrix.target-chip }} \
              --report-file reports/${{ matrix.test-file }}.md \
              --cleanup=3 \
              --get-metadata \
              -v
            python utils/find_duplicate_models.py -s -r ./test-onnx -o reports/duplicates.json

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_${{ matrix.test-file }}_onnx_md
          path: ./test-suite/alt_e2eamdshark/reports/${{ matrix.test-file }}.md

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_${{ matrix.test-file }}_onnx_json
          path: ./test-suite/alt_e2eamdshark/reports/${{ matrix.test-file }}.json

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_${{ matrix.test-file }}_duplicates_json
          path: ./test-suite/alt_e2eamdshark/duplicates.json

  push_artifacts:
    needs: [e2eamdshark]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: merge_rocm_reports
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: rocm
            regression-blob: rocm
            device: hip
            target-chip: gfx942
            cache-dir: /home/runner/data/e2eamdshark/amdshark-test-suite-models-cache
          - name: merge_cpu_reports
            runs-on: linux-mi325-1gpu-ossci-nod-ai
            backend: llvm-cpu
            regression-blob: cpu
            device: local-task
            target-chip: x86_64-linux-gnu
            cache-dir: /home/runner/groups/aig_amdsharks/test-suite-ci-cache
    env:
      AZ_PUBLIC_KEY: ${{ secrets.AMD_SHARKPUBLIC_AZ_KEY }}
      CACHE_DIR: ${{ matrix.cache-dir }}
    steps:
      - name: Checkout Test Suite
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: nod-ai/AMD-SHARK-TestSuite
          path: test-suite
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: nod-ai/e2eamdshark-reports
          ref: main
          token: ${{ secrets.E2EAMDSHARK_GITHUB_TOKEN }}
          path: e2eamdshark-reports
      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"
      - name: "Setup alt test suite venv"
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 30
          max_attempts: 2
          retry_on: error
          shell: bash
          on_retry_command: echo "::warning::Setup alt test suite venv failed, retrying..."
          command: |
            sudo apt update
            sudo apt install wget
            python -m venv report_venv_alt
            source report_venv_alt/bin/activate
            pip install --upgrade pip
            pip install -r ./test-suite/alt_e2eamdshark/base_requirements.txt
            pip install -r ./test-suite/alt_e2eamdshark/iree_requirements.txt
            pip install --no-deps -r ./test-suite/alt_e2eamdshark/torch_mlir_requirements.txt
            pip install --pre --upgrade iree-base-compiler iree-base-runtime -f https://iree.dev/pip-release-links.html
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_amdshark-test-suite_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_amdshark-test-suite_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_amdshark-test-suite_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_amdshark-test-suite_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard1_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard1_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard1_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard1_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard2_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard2_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard2_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard2_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard3_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard3_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard3_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard3_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard1_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard1_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard1_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard1_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard2_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard2_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard2_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard2_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard3_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard3_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard3_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard3_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-vision-int8_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-vision-int8_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_vai-vision-int8_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-vision-int8_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_migraphx_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_migraphx_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_migraphx_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_migraphx_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_nlp-shard1_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard1_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_nlp-shard1_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard1_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_nlp-shard2_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard2_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_nlp-shard2_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard2_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_nlp-shard3_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard3_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_nlp-shard3_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard3_others_onnx_json


      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_1_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_1_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_1_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_1_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_2_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_2_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_2_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_2_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_3_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_3_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_3_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_3_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_4_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_4_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_4_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_4_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_5_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_5_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_5_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_5_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_gen_ai_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_gen_ai_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_gen_ai_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_gen_ai_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_graph_ml_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_graph_ml_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_graph_ml_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_graph_ml_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_nlp_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_nlp_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_nlp_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_nlp_others_onnx_json
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_validated_vision_others_onnx_md
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_validated_vision_others_onnx_md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci_reports_${{ matrix.backend }}_onnx_model_zoo_validated_vision_others_onnx_json
          path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_validated_vision_others_onnx_json
      # - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      #   with:
      #     name: ci_reports_${{ matrix.backend }}_onnxrt-iree-ep_onnx_md
      #     path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnxrt-iree-ep_onnx_md
      # - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      #   with:
      #     name: ci_reports_${{ matrix.backend }}_onnxrt-iree-ep_onnx_json
      #     path: ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnxrt-iree-ep_onnx_json
      - name: Merge Reports
        run: |
          source report_venv_alt/bin/activate

          python ./test-suite/alt_e2eamdshark/utils/merge_dicts.py \
          --sources ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard1_others_onnx_json/vai-hf-cnn-fp32-shard1_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard2_others_onnx_json/vai-hf-cnn-fp32-shard2_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-hf-cnn-fp32-shard3_others_onnx_json/vai-hf-cnn-fp32-shard3_others.json \
          --output ./e2eamdshark-reports/vai-hf-cnn-fp32_others.json \
          --report --report-file ./e2eamdshark-reports/vai-hf-cnn-fp32_others.md

          python ./test-suite/alt_e2eamdshark/utils/merge_dicts.py \
          --sources ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard1_others_onnx_json/vai-int8-p0p1-shard1_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard2_others_onnx_json/vai-int8-p0p1-shard2_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-int8-p0p1-shard3_others_onnx_json/vai-int8-p0p1-shard3_others.json \
          --output ./e2eamdshark-reports/vai-int8-p0p1_others.json \
          --report --report-file ./e2eamdshark-reports/vai-int8-p0p1_others.md

          python ./test-suite/alt_e2eamdshark/utils/merge_dicts.py \
          --sources ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard1_others_onnx_json/nlp-shard1_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard2_others_onnx_json/nlp-shard2_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_nlp-shard3_others_onnx_json/nlp-shard3_others.json \
          --output ./e2eamdshark-reports/nlp_others.json \
          --report --report-file ./e2eamdshark-reports/nlp_others.md

          python ./test-suite/alt_e2eamdshark/utils/merge_dicts.py \
          --sources ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_1_others_onnx_json/onnx_model_zoo_computer_vision_1_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_2_others_onnx_json/onnx_model_zoo_computer_vision_2_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_3_others_onnx_json/onnx_model_zoo_computer_vision_3_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_4_others_onnx_json/onnx_model_zoo_computer_vision_4_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_computer_vision_5_others_onnx_json/onnx_model_zoo_computer_vision_5_others.json \
          --output ./e2eamdshark-reports/onnx_model_zoo_computer_vision_others.json \
          --report --report-file ./e2eamdshark-reports/onnx_model_zoo_computer_vision_others.md

          python ./test-suite/alt_e2eamdshark/utils/merge_dicts.py \
          --sources ./e2eamdshark-reports/vai-int8-p0p1_others.json \
          ./e2eamdshark-reports/vai-hf-cnn-fp32_others.json \
          ./e2eamdshark-reports/nlp_others.json \
          ./e2eamdshark-reports/onnx_model_zoo_computer_vision_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_amdshark-test-suite_others_onnx_json/amdshark-test-suite_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_vai-vision-int8_others_onnx_json/vai-vision-int8_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_migraphx_others_onnx_json/migraphx_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_gen_ai_others_onnx_json/onnx_model_zoo_gen_ai_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_graph_ml_others_onnx_json/onnx_model_zoo_graph_ml_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_nlp_others_onnx_json/onnx_model_zoo_nlp_others.json \
          ./e2eamdshark-reports/ci_reports_${{ matrix.backend }}_onnx_model_zoo_validated_vision_others_onnx_json/onnx_model_zoo_validated_vision_others.json \
          --output ./e2eamdshark-reports/combined_reports_others.json \
          --report --report-file ./e2eamdshark-reports/combined_reports_others.md

      - name: Push status artifacts
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          date=$(date '+%Y-%m-%d')
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/vai-hf-cnn-fp32_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/vai-int8-p0p1_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/amdshark-test-suite_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/vai-vision-int8_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/migraphx_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/nlp_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_computer_vision_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_gen_ai_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_graph_ml_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_nlp_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_validated_vision_others
          mkdir -p ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/combined-reports_others
          cp vai-hf-cnn-fp32_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/vai-hf-cnn-fp32_others/summary.md
          cp vai-int8-p0p1_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/vai-int8-p0p1_others/summary.md
          cp nlp_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/nlp_others/summary.md
          cp onnx_model_zoo_computer_vision_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_computer_vision_others/summary.md
          cp ci_reports_${{ matrix.backend }}_amdshark-test-suite_others_onnx_md/amdshark-test-suite_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/amdshark-test-suite_others/summary.md
          cp ci_reports_${{ matrix.backend }}_vai-vision-int8_others_onnx_md/vai-vision-int8_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/vai-vision-int8_others/summary.md
          cp ci_reports_${{ matrix.backend }}_migraphx_others_onnx_md/migraphx_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/migraphx_others/summary.md
          cp ci_reports_${{ matrix.backend }}_onnx_model_zoo_gen_ai_others_onnx_md/onnx_model_zoo_gen_ai_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_gen_ai_others/summary.md
          cp ci_reports_${{ matrix.backend }}_onnx_model_zoo_graph_ml_others_onnx_md/onnx_model_zoo_graph_ml_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_graph_ml_others/summary.md
          cp ci_reports_${{ matrix.backend }}_onnx_model_zoo_nlp_others_onnx_md/onnx_model_zoo_nlp_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_nlp_others/summary.md
          cp ci_reports_${{ matrix.backend }}_onnx_model_zoo_validated_vision_others_onnx_md/onnx_model_zoo_validated_vision_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/onnx_model_zoo_validated_vision_others/summary.md
          cp combined_reports_others.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/combined-reports_others/summary.md
          git add $date
          git commit -m "add CI status reports for e2eamdshark for ${{ matrix.backend }}"
          git push origin main
        working-directory: ./e2eamdshark-reports

      - name: Regression Reports
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 30
          max_attempts: 2
          retry_on: error
          shell: bash
          on_retry_command: echo "::warning::Regression reports failed, retrying..."
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            source report_venv_alt/bin/activate
            cd test-suite
            mkdir latest
            mkdir baseline
            wget https://amdsharkpublic.blob.core.windows.net/ciartifacts/latest-test-suite/combined_reports_others_${{ matrix.backend }}.json -O latest/combined_reports_others_${{ matrix.backend }}.json
            wget https://amdsharkpublic.blob.core.windows.net/ciartifacts/baseline-test-suite/combined_reports_others_${{ matrix.regression-blob }}.json -O baseline/combined_reports_others_${{ matrix.backend }}.json
            cd ..

            python ./test-suite/alt_e2eamdshark/utils/check_regressions.py \
              --new ./e2eamdshark-reports/combined_reports_others.json \
              --old ./test-suite/latest/combined_reports_others_${{ matrix.backend }}.json \
              --report-file ./e2eamdshark-reports/yesterday_comparison.md \
              --perf_tol_regression=0.05 \
              --perf_tol_progression=0.05

            cat "e2eamdshark-reports/yesterday_comparison.md" || echo "[WARN] yesterday_comparison.md 1 not found or unreadable"

            # --- Recheck for Regression Models ---
            echo "================ starting recheck for regression models ================"
            # generate a json with model name and old status
            MD_FILE="e2eamdshark-reports/yesterday_comparison.md"
            python ./test-suite/alt_e2eamdshark/utils/extract_model_old_new_status_from_md.py "$MD_FILE" || echo "[WARN] Failed to extract model old/new status"
            cat "model_old_new_status.json" || echo "[WARN] model_old_new_status.json not generated"

            JSON_FILE="model_old_new_status.json"
            python ./test-suite/alt_e2eamdshark/utils/extract_regression_model_names.py "$JSON_FILE" || echo "[WARN] Failed to extract regression models from json"
            cat "regression_models.txt" || echo "[WARN] regression_models.txt not generated"

            cd test-suite/alt_e2eamdshark/ || echo "failed to cd into test-suite/alt_e2eamdshark/"
            REGRESSION_MODELS="$PWD/../../regression_models.txt"
            python ./run.py \
               -r ./test-onnx \
               --report \
               --testsfile $REGRESSION_MODELS \
               -b ${{ matrix.backend }} \
               -d ${{ matrix.device }} \
               -c ${{ matrix.target-chip }} \
               --report-file current_result.md \
               --mode=cl-onnx-iree \
               --cleanup=3 \
               --get-metadata \
               -v || echo "[WARN] run.py Regression test execution failed"
            cd ../..

            REGRESSION_MODELS="regression_models.txt"
            BASELINE_JSON="model_old_new_status.json"
            CURRENT_JSON="test-suite/alt_e2eamdshark/current_result.json"
            REPORT_MD="e2eamdshark-reports/yesterday_comparison.md"

            if [[ ! -f "$REGRESSION_MODELS" ]]; then
              echo "[WARN] regression_models.txt missing — skipping per-model updates"
            else
              while IFS= read -r MODEL; do
                # skip empty lines
                [[ -z "$MODEL" ]] && continue

                echo "Processing model: $MODEL"

                python test-suite/alt_e2eamdshark/utils/check_model_status_and_remove.py \
                  "$MODEL" \
                  "$BASELINE_JSON" \
                  "$CURRENT_JSON" \
                  "$REPORT_MD" || echo "[WARN] Failed to process model: $MODEL in check_model_status_and_remove.py"

              done < "$REGRESSION_MODELS"
            fi

            cat "e2eamdshark-reports/yesterday_comparison.md" || echo "[WARN] yesterday_comparison.md 2 not found or unreadable"

            echo "================ done recheck for regression models ================"


            python ./test-suite/alt_e2eamdshark/utils/check_regressions.py \
              --new ./e2eamdshark-reports/combined_reports_others.json \
              --old ./test-suite/baseline/combined_reports_others_${{ matrix.backend }}.json \
              --report-file ./e2eamdshark-reports/baseline_comparison.md \
              --perf_tol_regression=0.1 \
              --perf_tol_progression=0.1

            az storage blob upload --account-name amdsharkpublic --container-name ciartifacts \
              --name latest-test-suite/combined_reports_others_${{ matrix.backend }}.json \
              --file ./e2eamdshark-reports/combined_reports_others.json \
              --account-key ${AZ_PUBLIC_KEY} --overwrite

      - name: Push regression artifacts
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          date=$(date '+%Y-%m-%d')
          cp yesterday_comparison.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/combined-reports_others/yesterday_comparison.md
          cp baseline_comparison.md ${date}/ci_reports_onnx_dup/${{ matrix.backend }}/combined-reports_others/baseline_comparison.md
          git add $date
          git commit -m "add CI regression reports for e2eamdshark for ${{ matrix.backend }}"
          git push origin main
        working-directory: ./e2eamdshark-reports
