import numpy as np
import onnxruntime


# the generated or checked in onnx file must always be called
# model.onnx
# This file forms middle of the runmodel.py for this test
# which is generated by run.py script in root of e2eshark
# test dir
# <e2eshark>/tools/stubs/onnxstartmodel.py
# this model.py
# <e2eshark>/tools/stubs/onnxendmodel.py
# are concatenated in that order to form
# <test-run dir>/onnx/<test category>/<test name>/runmodel.py
# which is run to run the model to generate output
# Leave the above comment in the file

# insert here any onnx API call to generate onnx file if
# not using a checked in onnx model


# to locally test, can uncomment the line below
# comment it back for launching from run.py as this will be set
# with full path to onnx to allow running in a separate run dir
# session = onnxruntime.InferenceSession("model.onnx", None)


# fill the lines that set test_input and onnx_output
# these two are special names and should not be changed
test_input = np.random.rand(1, 3, 224, 224).astype(np.float32)

# Get the name of the input of the model
input_name = session.get_inputs()[0].name

# call inference session
onnx_output = [session.run([], {input_name: test_input})[0]]
